apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "parking-bordeaux-metropole.fullname" . }}-compute-minima
  labels:
    {{- include "parking-bordeaux-metropole.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.computeMinima.schedule | quote }}
  timeZone: {{ .Values.computeMinima.timeZone }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: compute-minima
            image: "{{ .Values.computeMinima.image.repository }}:{{ .Values.computeMinima.image.tag }}"
            imagePullPolicy: {{ .Values.computeMinima.image.pullPolicy }}
            env:
            {{- with .Values.computeMinima.database }}
            - name: DB_HOST
              value: {{ .host }}
            - name: DB_NAME
              value: {{ .name }}
            - name: DB_USER
              value: {{ .user }}
            - name: DB_PASSWORD
              value: {{ .password }}
            {{- end }}
            envFrom:
            - secretRef:
                name: {{ include "parking-bordeaux-metropole.fullname" . }}-compute-minima
          restartPolicy: OnFailure
