apiVersion: v1
kind: Service
metadata:
  name: {{ include "parking-saint-jean.fullname" . }}-back
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
  selector:
    {{- include "parking-saint-jean.selectorLabels" . | nindent 4 }}
    component: back
